### ISSUE TITLE
Consider background contain option for full page

### ISSUE THREAD

**Issue by jasonsturges** [jasonsturges/jasonsturges.github.io#3]
Not particularly fond of the current photo pages.  Designed to fit content, experiment with contain or cover.  Also dependent on future of exif data added to the view.

html
```html
<html class="full" lang="en">
```

css
```css
.full {
    background: url('http://placehold.it/1920x1080') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
}
```
