### ISSUE TITLE
Navbar top margin and layout

### ISSUE THREAD

**Issue by jasonsturges** [jasonsturges/jasonsturges.github.io#4]
Top margin appears to have been lost along the way.

Additional prototyping:
- fixed-top, reassess this vs static-top
- front page transparent vs black
- higher contrast, in general

```css
body {
    margin-top: 50px; /* Required margin for .navbar-fixed-top. 
                         Remove if using .navbar-static-top. 
                         Change if height of navigation changes. */
}
```
